### ISSUE TITLE
`rasterstats.__version__` attribute not present

### ISSUE THREAD

**Issue by maxalbert** [perrygeo/python-rasterstats#102]
It seems that there is no `rasterstats.__version__` attribute, which makes it difficult to quickly check the installed version from within Python. It would be great if this could be provided. Thanks!

**Comment by perrygeo** [comment]
:+1: agreed, I'll add to the next version. Gotta find a way to avoid hardcoding the version string in multiple places but I'm sure someone has solved it.

**Comment by maxalbert** [comment]
I think some packages keep a separate file (e.g. `version.py`) which only contains the version string and then add some logic to import that in `__init__.py` and wherever else you need it.

This page collects a bunch of possible solutions: http://python-packaging-user-guide.readthedocs.org/en/latest/single_source_version/

**Comment by perrygeo** [comment]
I just released 0.9.2 which should have the __version__ attr. Thanks @maxalbert !

**Comment by maxalbert** [comment]
Wow, that was lightning fast! Thanks! :)
