### ISSUE TITLE
np.unique return_counts option requires numpy>=1.9

### ISSUE THREAD

**Issue by sgoodm** [perrygeo/python-rasterstats#112]
requirements currently only enforce numpy>=1.8

https://docs.scipy.org/doc/numpy-1.10.1/reference/generated/numpy.unique.html

**Comment by perrygeo** [comment]
@sgoodm Nice catch! If we bump the requirement to `numpy>=1.9` do you think that will cause an issue for anyone?

**Comment by sgoodm** [comment]
i took a quick look at the 1.9 release notes and nothing stood out. there were some changes to percentiles and mask fills but they shouldn't cause any problems.

for reference:
https://docs.scipy.org/doc/numpy-1.10.1/release.html#numpy-1-9-0-release-notes

**Comment by perrygeo** [comment]
Thanks! Closed in 0cf1586603ed151c40f2ddda5ec30a17bdf8d0e1
