### ISSUE TITLE
Allow for raster instances as arguments for zonal_stats

### ISSUE THREAD

**Issue by postfalk** [perrygeo/python-rasterstats#113]
Raster.__init__ currently allows for passing file names and numpy arrays. Why is it not possible to pass actual GDAL raster instances?

I might work on this.

**Comment by perrygeo** [comment]
By "GDAL raster instances" are you referring to objects of type `rasterio._io.RasterReader`?

Support for the `osgeo.gdal` python module was dropped in 0.7 with no plans to bring it back. Long story made short: `osgeo` python bindings are not suitable for production systems due to side effects of simply importing them. See 

* https://github.com/Toblerity/Fiona/issues/92
* https://github.com/geopandas/geopandas/issues/214

**Comment by postfalk** [comment]
Oh, I overlooked that rasterio doesn't rely on the python gdal binding. Sorry, for not looking this up thoroughly enough. I wish the documentation for rasterio would be better just gave up on implementing my workflow in rasterio and thought I could cut a corner. Thank you for you immediate response.

**Comment by perrygeo** [comment]
We're working on improving [rasterio docs](https://github.com/mapbox/rasterio/issues?q=is%3Aissue+is%3Aopen+label%3Adocs) for a 1.0 release later this year. It would be extremely helpful if you could point out where you got hung up, maybe share your gdal script so we can clarify how to do the same task is rasterio. Thanks @postfalk !

**Comment by postfalk** [comment]
It was just the basic raster creation from scratch (well an two dimensional Numpy array). Something like

```python
array = numpy.reshape(
    numpy.asarray(list_of_numbers.astype(int),
    (nrows, ncols))
new_driver = ImageDriver('Gtiff')
ds = new_driver.Create(
    'image.tif',
    ncols,
    nrows,
    1,
    gdal.GDT_Int32)
ds.SetGeoTransform((xllcorner,
    cellsize,
    0,
    yllcorner + nrows * cellsize,
    0,
    - cellsize))
ds.SetProjection(wkt_proj_string)
ds.GetRasterBand(1).WriteArray(array)
ds.GetRasterBand(1).SetNoDataValue(99999)
ds.FlushCache()
```
I managed to create a tif file in rasterio with these parameters, but the values were all zero and the resolution not right either. I do not have this code on hand but I could try to reproduce if you like.

I am also aware of the fact that statistics can be done directly on a numpy array, however my application requires some higher level of decoupling as well as writing the rasters actually to disc.

Thank you
