### ISSUE TITLE
Numpy array zonal_stat

### ISSUE THREAD

**Issue by LorenzoBottaccioli** [perrygeo/python-rasterstats#114]
Hi,

Is it possible to pass to zonal_stats an numpy array objcet like:

```
import gdal
import geopandas as gpd
from rasterstats import zonal_stats

geodf=pd.read_file("mysph",crs='4326').drop('Atr',axis=1)
rast = gdal.Open("myraster")
raster=rast.GetRasterBand(1).ReadAsArray(0,0, rast.RasterXSize,ast.RasterYSize).astype(numpy.float)

zonal_stats=(geodf,raster)
```

If I run this code I get:

ValueError: Must specify affine for numpy arrays

**Edit 1:**
Hi,

I have gone a littele bit forward, but I still get errors:

```
import gdal
import geopandas as gpd
from rasterstats import zonal_stats
from affine import Affine
geodf=pd.read_file("mysph",crs='4326').drop('Atr',axis=1)
rast = gdal.Open("myraster")
raster=rast.GetRasterBand(1).ReadAsArray(0,0, rast.RasterXSize,ast.RasterYSize).astype(numpy.float)

zonal_stats=(geodf['geometry'],raster,affine=Affine,transform='transform')
```

But I get this error:
```
TypeError                                 Traceback (most recent call last)
<ipython-input-90-a0288c358867> in <module>()
----> 1 z(geodf['geometry'],raster,affine=Affine,transform='transform')

/usr/local/lib/python2.7/dist-packages/rasterstats/main.pyc in zonal_stats(*args, **kwargs)
     19 
     20 def zonal_stats(*args, **kwargs):
---> 21     return list(gen_zonal_stats(*args, **kwargs))
     22 
     23 

/usr/local/lib/python2.7/dist-packages/rasterstats/main.pyc in gen_zonal_stats(vectors, raster, layer, band_num, nodata, affine, stats, all_touched, categorical, category_map, add_stats, raster_out, prefix, geojson_out, **kwargs)
    134             geom_bounds = tuple(geom.bounds)
    135 
--> 136             fsrc = rast.read(bounds=geom_bounds)
    137 
    138             # create ndarray of rasterized geometry

/usr/local/lib/python2.7/dist-packages/rasterstats/io.pyc in read(self, bounds, window, masked)
    266 
    267         if bounds:
--> 268             win = bounds_window(bounds, self.affine)
    269         elif window:
    270             win = window

/usr/local/lib/python2.7/dist-packages/rasterstats/io.pyc in bounds_window(bounds, affine)
    137     """
    138     w, s, e, n = bounds
--> 139     row_start, col_start = rowcol(w, n, affine)
    140     row_stop, col_stop = rowcol(e, s, affine, op=math.ceil)
    141     return (row_start, row_stop), (col_start, col_stop)

/usr/local/lib/python2.7/dist-packages/rasterstats/io.pyc in rowcol(x, y, affine, op)
    128     """ Get row/col for a x/y
    129     """
--> 130     r = int(op((y - affine.f) / affine.e))
    131     c = int(op((x - affine.c) / affine.a))
    132     return r, c

TypeError: unsupported operand type(s) for -: 'float' and 'property'
```

**Comment by perrygeo** [comment]
@LorenzoBottaccioli the raster input to zonal stats must be an instance of the [`Raster` class](https://github.com/perrygeo/python-rasterstats/blob/master/src/rasterstats/io.py#L193) which abstracts the differences between a raster on disk and a numpy array.

So in this example, `r1` and `r2` can be passed to zonal stats with the same results

    r1 = Raster(raster)

    with rasterio.open(raster) as src:
        arr = src.read(1)
        affine = src.affine
        nodata = src.nodata

    r2 = Raster(arr, affine, nodata)

**Comment by perrygeo** [comment]
Three issues with the code above:
* try leaving off the `transform` argument (that's the deprecated GDAL-style transform)
* the argument for `affine` needs to be an *instance* of an affine object, not the class itself. (see http://www.perrygeo.com/python-affine-transforms.html for more on affines and transforms)
* importing `osgeo.gdal` in the same process as `rasterstats` is discouraged - they be mixed with other code that touches libgdal in the same process due to unsafe memory management and global state.

The following code is all you need:

```
import rasterio
import geopandas as gpd
from rasterstats import zonal_stats

geodf=pd.read_file("mysph",crs='4326').drop('Atr',axis=1)
with rasterio.open("myraster") as src:
    array = src.read(1)
    affine = src.affine
zonal_stats = (geodf['geometry'], array, affine=affine)
```

**Comment by debboutr** [comment]
shouldn't it be..
geodf=gpd.read_file("mysph",crs='4326').drop('Atr',axis=1)

above

**Comment by perrygeo** [comment]
possibly? I was just copying @LorenzoBottaccioli's code above so he could comment on that

**Comment by ccabanero** [comment]
Hello all,

Just sharing a slightly modified code snippet that helped me solve this same issue in 2021 with new versions of gdal (3.2.1) and rasterio (v1.2.1)

````
    import rasterio
    from rasterstats import zonal_stats
    import geopandas as gpd

    boundaries = gpd.read_file('zip+s3://my-s3-bucket/my-zipped-shapefile.zip')

    with rasterio.open("/vsis3/{0}/{1}".format('my-s3-bucket', 'my-cloud-optimized-geotiff.tif')) as src:
      array = src.read(1)
      trans = src.transform # --> here do src.transform instead of src.affine

      zs = zonal_stats(boundaries, array, affine=trans)
````

**Comment by Havi-muro** [comment]
Hi,
I'm using the snippet that ccabanero provided. zonal_stats is extracting the values for only 6 of my 500 polygons. The polygons are non-contiguous and scattered over raster. Do you know if that could be the problem?
`
geo = gpd.read_file(geodir)
rasls_alb = rasdir+'\\alb_TOA_LAI2020-09-08.tif'

with rio.open(rasls_alb) as src:
     array = src.read(1)
     trans = src.transform # --> here do src.transform instead of src.affine

zs = zonal_stats(geoalb, array, affine=trans)

df = pd.DataFrame(zs)
print(df.loc[45])
count    1.000000
min      5.938412
max      5.938412
mean     5.938412
Name: 45, dtype: float64
`
Thanks!
