### ISSUE TITLE
rasterstats/gdal interaction: Unable to perform coordinate transformations

### ISSUE THREAD

**Issue by Jenders74** [perrygeo/python-rasterstats#118]
Importing rasterstats before opening a grib file with gdal like this:

```
from osgeo import gdal
import rasterstats
src_ds = gdal.Open(r'H:\test.grib2')
```

makes the grib file lose its projection/spatial reference system:

> WARNING:rasterio._gdal:CPLE_AppDefined in b'Unable to perform coordinate transformations, so the correct\nprojected geotransform could not be deduced from the lat/long\ncontrol points.  Defaulting to ungeoreferenced.'

Removing the import rasterstats statement and running the rest from a fresh interpreter works fine.

I got the grib file like this:

```
import urllib.request
url = r'http://nomads.ncep.noaa.gov/cgi-bin/filter_hrrr_2d.pl?file=hrrr.t16z.wrfsfcf15.grib2&lev_1000_m_above_ground=on&var_REFD=on&leftlon=-91&rightlon=-73&toplat=43&bottomlat=35&dir=%2Fhrrr.20160628'
out_path = r'H:\test.grib2'
tfile  = urllib.request.urlopen(url)
f = open(out_path, 'wb')
f.write(tfile.read())
f.close()
```

Python 3.4.4
rasterstats 0.10.3
gdal 2.0.0

Not sure of this is a rasterstats issue or a gdal issue.

**Comment by perrygeo** [comment]
`osgeo.gdal` python bindings use global state and cannot be used safely with other modules that link to `libgdal` such as Rasterio (upon which rasterstats depends).

You can recreate the same issue by using `import rasterio` or any other module which links to libgdal. I'm closing this ticket as it's not directly related to rasterstats but I'd encourage you to open a ticket in Rasterio: https://github.com/mapbox/rasterio/issues
