### ISSUE TITLE
ValueError raised when non-overlapping geometry and raster

### ISSUE THREAD

**Issue by ozak** [perrygeo/python-rasterstats#119]
Hi @perrygeo,

it seems the current version has trouble when intersection the shape with a rester, when they do not overlap. In the old version one would get a ``None`` for all stats, but in the current version it raises the following error message:

    ValueError: could not broadcast input array from shape (1398,3) into shape (2,3)

I tried running the same code and data using a version of rasterstats before we eliminated the ``georaster`` dependency #76 and it worked like a charm.

I think this might be related to #108 and #107. Not sure if it is easily solvable...I will try to take a look, but I have to reacquaint myself with the new code.

**Comment by perrygeo** [comment]
@ozak Can you provide some data to reproduce? I'd like to get this case in the unit tests and get it fixed asap.

**Comment by ozak** [comment]
Here's the [https://www.dropbox.com/sh/1y85js02s1mzjic/AACrK7RRqyf5AIX3ZGiF8DNWa?dl=0](data) the code to replicate it is

    from rasterstats import zonal_stats
    stats = zonal_stats('./PRT_adm3.shp', 'Fusca.tif', copy_properties=True, all_touched=True)

Although one could think that part of the problem comes from the size of the geometries (much smaller than the cells), and indeed using larger regions did not generate the issue with this raster, but they did generate the same issue with other rasters. In any case, even if the geometries are smaller then the cells one should get a result as in the old code.

**Comment by perrygeo** [comment]
Thanks @ozak, I downloaded the data and have a few questions

It looks like the shapes (Europe) do not intersect a valid data cell for that raster (Africa).

![screen shot 2016-07-03 at 3 10 43 pm](https://cloud.githubusercontent.com/assets/1151287/16547105/78c18fc8-4130-11e6-91ff-420e334647e4.png)

 In this case, we'd expect to see every `stats` item with a count of `0` and `None` for the stats. This is exactly what I get with the current master and the current release `0.10.3`. In other words, **I can't reproduce the `ValueError` that you're getting**. What version are you using to get these results?

Also note that [the `copy_properties` argument has been deprecated](https://github.com/perrygeo/python-rasterstats/wiki/Migrating-to-1.0#removal-of-copy_properties) in favor of using `geojson_out` to better interoperate with GeoJSON utilities.

**Comment by perrygeo** [comment]
Here's the code I used to confirm. Note that it does not raise an error and ll the counts are zero

```
from rasterstats import zonal_stats

shp = "/Users/mperry/Downloads/RasterStats/PRT_adm3.shp"
tif = "/Users/mperry/Downloads/RasterStats/Fusca.tif"

stats = zonal_stats(shp, tif, all_touched=True)
assert sum(s['count'] for s in stats) == 0
```

**Comment by sgoodm** [comment]
pretty sure this is a bug from an older version of rasterio. try updating it

**Comment by ozak** [comment]
Indeed...I updated to ``rasterio-0.36.0`` and it worked fine. Thanks!
