### ISSUE TITLE
Rasterstats install on Anaconda

### ISSUE THREAD

**Issue by rmuellerjr** [perrygeo/python-rasterstats#121]
I seem to be having trouble installing rasterstats successfully in the windows 64bit environment (Windows 7 or Server 2012). I am currently using Anaconda (python 2.7,also tried 3.4) to install, with either the rasterio install instructions (pip install GDAL-2.0.2-cp27-none-win32.whl and rasterio-0.34.0-cp27-cp27m-win32.whl) or via conda forge (https://github.com/conda-forge/rasterio-feedstock). 

In both cases gdal/rasterio will run as expected but when I try to install rasterstats (via rasterstats-0.10.3-py2-none-any.whl or pip install rasterstats) I receive an error "GeoVersion" or "GdalVersion" not found, accompanyied with a "python setup.py egg error code 1".

I've checked that the corresponding package is installed and the version is up to date. Any ideas what may be causing the install issue?

Thanks for your time.
-Bob

**Comment by perrygeo** [comment]
Can you can confirm that Rasterio is working properly? I've had mixed results with the quality of the conda-forge builds.

And can you provide a more detailed traceback as a gist? I'd like to see what specifically is failing in setup.py. There is no mention of "GeoVersion" or "GdalVersion" nor any setup-time dependencies so I suspect it's related to packaging of one of rasterstats dependencies.

**Comment by phobson** [comment]
FWIW, it appears the GDAL/rasterio/fiona debacle in conda-forge has been straightened out. Mistakes were made. Lessons learned.

@rmuellerjr can you try again in a fresh environment?

**Comment by perrygeo** [comment]
@phobson out of curiosity, is there a post-debacle summary of the mistakes and lessons? I've read bits and pieces but still don't have a big picture sense of what went wrong and what we can do to prevent it from happening again.

**Comment by phobson** [comment]
My understanding is that a compiler-linker-helper-doohickey[1] package called `toolchain` was created and deployed as a dependency to a bunch of python packages with built C-extensions. Short version is that `toolchain` didn't quite work as a expected. Debugging and getting it fixed took a bit of time. 

[1]
> I don't know what I'm saying
--Lucille Bluth

**Comment by phobson** [comment]
Oh -- That was the mistake. The lesson is that conda-forge now has an "enhancement proposal" policy/workflow that will provide a way to test out these more ecosystem-wide changes before (potentially broken) packages get uploaded to the channel. 

I don't know if any other this is formally codified yet. I heard that this came out of discussions at the SciPy conference.

**Comment by perrygeo** [comment]
thanks for the info @phobson 

@rmuellerjr - I'm going to close for now, if you're still having issues, please re-open with details. Thanks!

**Comment by rmuellerjr** [comment]
@perrygeo - Thanks for looking into things. I'm finally getting back around to getting this figured out. I will re-open if necessary.
