### ISSUE TITLE
NAN in stats

### ISSUE THREAD

**Issue by pwt-nf** [perrygeo/python-rasterstats#123]
Hi,

Thanks for the great tool. Im having an issue wherein I get pixel counts but all the stats are `nan`. The raster is a `.tif` created in GRASS type is `Float64`. First attempt was with a multi-polygon and small areas worked. There are some `nodata` values that overlap with the json.

Let me know if I can provide anything to assist in troubleshooting.

`> rio zonalstats pine_creek/pc_prop.geojson --nodata 0 --all-touched -r pine_creek/cdl.tif --prefix cdl_ > pine_creek/sc_property_cye.geojson`

Peter

**Comment by perrygeo** [comment]
Can you provide a small subset of the data to reproduce this? Generally if there are `NaN` in the float rasters, they *should* be treated as nodata and ignored (per https://github.com/perrygeo/python-rasterstats/pull/116).

**Comment by pwt-nf** [comment]
Here's a [link](https://drive.google.com/file/d/0B9-9Vlx0SkkFaXZKRkN0c2pPMVk/view?usp=sharing) to the raster and geojson I was using. Thanks for looking into it!

**Comment by perrygeo** [comment]
Thanks Peter, I can confirm the problem and will try to come up with a solution today or over this weekend.

**Comment by pwt-nf** [comment]
Thanks Matthew!

On Sep 2, 2016 4:47 AM, Matthew Perry <notifications@github.com> wrote:

Thanks Peter, I can confirm the problem and will try to come up with a solution today or over this weekend.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_perrygeo_python-2Drasterstats_issues_123-23issuecomment-2D244353938&d=DQMCaQ&c=euGZstcaTDllvimEN8b7jXrwqOf-v5A_CdpgnVfiiMM&r=j3vrwyB_XzA1ItrHU6OBJeNY7D44AKrpS3wnudWzRFQ&m=ZNNQ8nYMJuJUtEG0ClmN9edzgyBQjtgSe2mLS7xKyZE&s=osW23NfV04bOnhwdt7K8HKKmN2HzA-uUnlTPmeMKQ8A&e=>, or mute the thread<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AS3uDY4Ewk54MFcmPtZ7lGGld3O9NdEcks5qmAzMgaJpZM4Jo-2DO5&d=DQMCaQ&c=euGZstcaTDllvimEN8b7jXrwqOf-v5A_CdpgnVfiiMM&r=j3vrwyB_XzA1ItrHU6OBJeNY7D44AKrpS3wnudWzRFQ&m=ZNNQ8nYMJuJUtEG0ClmN9edzgyBQjtgSe2mLS7xKyZE&s=UAQlIRtLUudpOIuBdxrcKS_afJ-hB_qvcgu77IFylHk&e=>.




________________________________

This email has been scanned for spam and viruses by Proofpoint Essentials. Click here<https://us1.proofpointessentials.com/index01.php?mod_id=11&mod_option=logitem&mail_id=N5L3QKdlknAP&r_address=ptittmann%40newforests-us.com&report=1> to report this email as spam.

**Comment by pwt-nf** [comment]
@perrygeo would this change be in the `pip` version?

**Comment by perrygeo** [comment]
not yet as there are a few more issues to address before releasing version 0.11. I expect to have a release this weekend.
