### ISSUE TITLE
Enable use of Fiona slice iterators

### ISSUE THREAD

**Issue by lpinner** [perrygeo/python-rasterstats#125]
I ran into the following exception when trying to run gen_zonal_stats on a Fiona feature layer Collection that had been filtered using `Collection.items` method (used for [slicing and masking](http://toblerity.org/fiona/manual.html#slicing-and-masking-iterators))

```
Traceback (most recent call last):
  File "test.py", line 16, in <module>
    nodata=-999, all_touched=True)) #Oops...
  File "D:\conda\py35\lib\site-packages\rasterstats\main.py", line 141, in gen_zonal_stats
    for i, feat in enumerate(features_iter):
  File "D:\conda\py35\lib\site-packages\rasterstats\io.py", line 113, in <genexpr>
    features_iter = (parse_feature(x) for x in obj)
  File "D:\conda\py35\lib\site-packages\rasterstats\io.py", line 70, in parse_feature
    raise ValueError("Can't parse %s as a geojson Feature object" % obj)
TypeError: not all arguments converted during string formatting
```

The `items` generator iterates over tuples of (FID, feature) rather than just the feature you'd get when iterating over the Collection object.

My workaround is to extract just the features into a list:
```
        feature_items = feature_collection.items(bbox=(xmin, ymin, xmax, ymax))
        feature_items = [f[1] for f in feature_items]
        results = rasterstats.gen_zonal_stats(feature_items, etc...)
```
Test script and data illustrating the issue attached - [test.zip](https://github.com/perrygeo/python-rasterstats/files/448697/test.zip)

Would you consider adding support for filtered Fiona collections?

**Comment by perrygeo** [comment]
The function takes an iterable of features but it doesn't need to be a `list` per se. A generator would do the trick without realizing the entire dataset in memory:

    feature_items = feature_collection.items(bbox=(xmin, ymin, xmax, ymax))
    # Generator expression instead of list comprehension
    feature_items = (feat for i, feat in feature_items)
    results = rasterstats.gen_zonal_stats(feature_items, etc...)

**Comment by perrygeo** [comment]
The vector arg to zonal_stats is already pretty loose in terms of what it accepts (file paths, geojson-like data, etc) and that puts lots of io logic inside of the this library instead of exterior to it where it should ideally belong. If anything I'm inclined to start trimming down the accepted vector types and moving the io to a separate lib. On the other hand, I'd gladly accept a PR which added this functionality.

**Comment by lpinner** [comment]
Thanks @perrygeo - I used a list as the datasets are small and I have to reuse the features to run gen_zonal_stats on multiple rasters, but yes a generator would be fine if I was only reading the features once.

I had a look at io.py. I ended up with a last ditch attempt in the parse_feature func before the ValueError is raised. It worked, but just feels too hacky.

```
    #Fiona slice
    try:
       return parse_feature(obj[1])
    except (IndexError,TypeError):
       pass
```

My real issue is that a fiona iterable is not always the same. I think I prefer to understand what I'm passing around so I'll close this.
