### ISSUE TITLE
CLI flag for nodata

### ISSUE THREAD

**Issue by NewForestsUS** [perrygeo/python-rasterstats#138]
I'm working on a `HFA` raster ([Archive.zip](https://github.com/perrygeo/python-rasterstats/files/649852/Archive.zip)) wherein no data is referenced as `nan`. When I run 'raterstats' based on this geojson, the output says 0 for the count of nodata cells despite the fact that there are many.

[foo.txt](https://github.com/perrygeo/python-rasterstats/files/649865/foo.txt)

Thanks in advance for any guidance!

**Comment by perrygeo** [comment]
"nodata" refers to cells which are equal to a specified value, mostly for use with integral data types. "NaN" are not *necessarily* "nodata" (they could be cells where the result of some calculation yielded an incalculable value but it is still a valid floating data nonetheless) thus have slightly different semantics.  It's possible to have different nodata and NaN's as might be one interpretation of your `merged.img` raster.

![screen shot 2016-12-13 at 4 50 37 pm](https://cloud.githubusercontent.com/assets/1151287/21158749/da535a56-c154-11e6-84de-2ef756c4a45e.jpg)


Currently nans are just ignored in the calcs but are not explicitly counted.  See https://github.com/perrygeo/python-rasterstats/issues/105 for some ongoing discussion - we need to separate nodata from nan and report them differently.

**Comment by pwt-nf** [comment]
Thanks @perrygeo ! since I'm building the raster, I can attribute those cells as I please. Whats would be the best strategy/is it possible to give them a value that the current nodata result would track?

**Comment by sgoodm** [comment]
guessing this was solved but just in case

@NewForestsUS you can assign those cells any non-nan value (use your raster's nodata value if it already has one) and just pass it to rasterstats using the `nodata` option

@perrygeo, can close this one
