### ISSUE TITLE
Issues with importing rasterstats

### ISSUE THREAD

**Issue by PanditPranav** [perrygeo/python-rasterstats#139]
I am working on Windows system and when I try to import rasterstas it gives me this error

import rasterio
from rasterstats import zonal_stats

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-15-ecf251862e57> in <module>()
      1 import rasterio
----> 2 from rasterstats import zonal_stats

C:\Users\pspandit\AppData\Local\Continuum\Anaconda2\lib\site-packages\rasterstats\__init__.py in <module>()
      2 from .main import gen_zonal_stats, raster_stats, zonal_stats
      3 from .point import gen_point_query, point_query
----> 4 from rasterstats import cli
      5 from rasterstats._version import __version__
      6 

C:\Users\pspandit\AppData\Local\Continuum\Anaconda2\lib\site-packages\rasterstats\cli.py in <module>()
     14 
     15 @click.command(context_settings=SETTINGS)
---> 16 @cligj.features_in_arg
     17 @click.version_option(version=version, message='%(version)s')
     18 @click.option('--raster', '-r', required=True)

AttributeError: 'module' object has no attribute 'features_in_arg'

**Comment by perrygeo** [comment]
Can you try upgrading `cligj` to the latest version?

Details: `cligj.features_in_arg` requires [version 0.4](https://github.com/mapbox/cligj/blob/master/CHANGES.txt#L3). rasterstats specified this in the [`setup.py` file](https://github.com/perrygeo/python-rasterstats/blob/master/requirements.txt#L4).

**Comment by PanditPranav** [comment]
Yup, updating cligj worked... 

Thanks..
