### ISSUE TITLE
Question: Transform/Affine functions to match projections of Rasters and Shapefiles? 

### ISSUE THREAD

**Issue by PanditPranav** [perrygeo/python-rasterstats#153]
Hi there, 

This has been a great and fast package which has immensely helped me do some large calculations on rasters.  I have some rasters which are not projected with the same CRS as the shapefile and I am assuming the function 'gen_zonal_stats' handles the CRS transformation. Or do we have to manually transform rasters to same CRS as of shapefile running 'Zonal Stats' function?

**Comment by sgoodm** [comment]
This package does not handle projections. You need to provide vector and raster layers with matching projections 

See #4 #26

**Comment by perrygeo** [comment]
What @sgoodm said ☝️ 

I would recommend transforming the geometry of the vector data to match the raster. Reprojecting rasters requires resampling which alters the pixel values. But reprojecting vectors is generally safer and lossless as you are just moving the verticies in 2D.
