### ISSUE TITLE
Fully remove the use of the rasterio `affine` property

### ISSUE THREAD

**Issue by perrygeo** [perrygeo/python-rasterstats#155]
The `src.affine` property of Rasterio datasets is deprecated.

We do the right thing in `rasterstats.io` https://github.com/perrygeo/python-rasterstats/blob/a0eef4ee721ff68503c25e073561a98a71768a9d/src/rasterstats/io.py#L242

But elsewhere, in main and in the tests, we access the affine property directly.

Also we use the `affine` argument name everywhere - this should be changed (in a backwards compatible way) to `transform`

**Comment by gfairchild** [comment]
I've got a related question. If I pass in `src.transform` to the `affine` argument in `zonal_stats`, will things break? I haven't tried this yet, but I'm curious. Just looking ahead to `rasterio` 1.0.

**Comment by gfairchild** [comment]
I just answered my won question: the answer is no, things don't break. I just switched to `rasterio` 1.0a9, and passing `src.transform` to `affine` appears to be working perfectly.

**Comment by perrygeo** [comment]
We've moved over to using `transform` everywhere when talking to Rasterio dataset objects.

We're still using the `affine` parameter name for e.g. the keyword argument to `zonal_stats`. Not a high priority to change it.  Closing here for now.
