### ISSUE TITLE
Feature ID in zonal_stats

### ISSUE THREAD

**Issue by solomonvimal** [perrygeo/python-rasterstats#158]
Hi, 
Zonal stats in [this example ](http://nbviewer.jupyter.org/github/perrygeo/python-raster-stats/blob/master/docs/notebooks/Integrating%20with%20GeoPandas%20and%20Numpy.ipynb) shows a feature ID that is saved together with the statistics for each feature. I think this is a useful feature to have. But when I try to replicate this in rasterstats (v0.12.0), I am not sure why feature ID is not saved. Perhaps it has to do with how feature ID is stored in my shapefile? Can you please let me know if I am missing something.

Thanks,
Solomon

**Comment by perrygeo** [comment]
if you need to retain the attributes/properties of the feature, use the `features_out=True` keyword argument. This will output full geojson features with a `properties` key
