### ISSUE TITLE
Shell is not a LinearRing

### ISSUE THREAD

**Issue by Biaggio74** [perrygeo/python-rasterstats#162]
### Expectation
I try to get some zonal statistic from the example files provided in the repo.

### Re-produce the issue
zonal_stats works perfectly from the command line:
fio cat polygons.shp | rio zonalstats -r slope.tif

But when I run the following python code I got the error as below. 

```python
from rasterstats import zonal_stats, point_query
stats = zonal_stats('tests/data/polygons.shp', 'tests/data/slope.tif')

Shell is not a LinearRing
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-25-36e573360044> in <module>()
      1 from rasterstats import zonal_stats
----> 2 stats = zonal_stats('tests/data/polygons.shp', 'tests/data/slope.tif')

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/rasterstats/main.py in zonal_stats(*args, **kwargs)
     29     The only difference is that ``zonal_stats`` will
     30     return a list rather than a generator."""
---> 31     return list(gen_zonal_stats(*args, **kwargs))
     32 
     33 

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/rasterstats/main.py in gen_zonal_stats(vectors, raster, layer, band, nodata, affine, stats, all_touched, categorical, category_map, add_stats, zone_func, raster_out, prefix, geojson_out, **kwargs)
    148             geom = shape(feat['geometry'])
    149 
--> 150             if 'Point' in geom.type:
    151                 geom = boxify_points(geom, rast)
    152 

/Library/Frameworks/GEOS.framework/Versions/3B/Python/3.6/site-packages/shapely/geometry/base.py in type(self)
    350     @property
    351     def type(self):
--> 352         return self.geometryType()
    353 
    354     def to_wkb(self):

/Library/Frameworks/GEOS.framework/Versions/3B/Python/3.6/site-packages/shapely/geometry/base.py in geometryType(self)
    346 
    347     def geometryType(self):
--> 348         return geometry_type_name(self._geom)
    349 
    350     @property

/Library/Frameworks/GEOS.framework/Versions/3B/Python/3.6/site-packages/shapely/geometry/base.py in geometry_type_name(g)
     67 def geometry_type_name(g):
     68     if g is None:
---> 69         raise ValueError("Null geometry has no type")
     70     return GEOMETRY_TYPES[lgeos.GEOSGeomTypeId(g)]
     71 

ValueError: Null geometry has no type
```

### Operating system
macOS High Sierra, version 10.13.3

### Package info
Name: rasterstats
Version: 0.12.1
Summary: Summarize geospatial raster datasets based on vector geometries
Home-page: https://github.com/perrygeo/python-raster-stats
Author: Matthew Perry
Author-email: perrygeo@gmail.com
License: BSD
Location: /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages
Requires: shapely, simplejson, fiona, rasterio, cligj, numpy

**Comment by perrygeo** [comment]
@Biaggio74 Interesting results. Thanks for the detailed report!

I'm not able to reproduce the error using the test data.

```
⭆ python
Python 3.6.1 (v3.6.1:69c0db5050, Mar 21 2017, 01:21:04)
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from rasterstats import zonal_stats, point_query
>>> stats = zonal_stats('tests/data/polygons.shp', 'tests/data/slope.tif')
>>> stats
[{'min': 6.575114727020264, 'max': 22.273418426513672, 'mean': 14.660084635416666, 'count': 75}, {'min': 16.940950393676758, 'max': 82.69043731689453, 'mean': 56.60576171875, 'count': 50}]
```

What version of Shapely are you using? Can you try to reinstall with --upgrade and see if you get the same results?

**Comment by Biaggio74** [comment]
I re-installed Shapely in a fresh virtual Python environment. Now it works fine from the command line.
My Shapely version is: 1.6.4.post1
Here is my whole pip freeze:
`(venv) ~/projects/python-rasterstats (master) $ pip freeze
affine==2.1.0
click==6.7
click-plugins==1.0.3
cligj==0.4.0
Fiona==1.7.11.post1
munch==2.2.0
numpy==1.14.2
pyparsing==2.2.0
rasterio==0.36.0
rasterstats==0.12.1
Shapely==1.6.4.post1
simplejson==3.13.2
six==1.11.0
snuggs==1.4.1`

But I am using Jupyter Notebook and it has a strange result. When I fire up a notebook from the virtualenv the notebooks loads. These three lines codes has proper result, as per the attached image. 

<img width="1094" alt="jupyter_notebook" src="https://user-images.githubusercontent.com/11397475/37569261-11c75e2e-2ae0-11e8-9843-3df678178c38.png">

But if I re-run the individual cells then I got the same error as explained before.

<img width="1098" alt="error-jupyter" src="https://user-images.githubusercontent.com/11397475/37569324-eeabb402-2ae0-11e8-9cc3-7c0ffa234e80.png">


I have installed Jupyter with pip install jupyterlab. So I am not using Conda.

Anyhow, It seems this can be a Jupyter issue, so it is fine for me if you prefer to close this issue ticket.

**Comment by perrygeo** [comment]
Thanks for the report. This is strange, I'd love to know how you solve it. But in terms of this repo, there's nothing I can do here.

lets continue the conversation -> https://github.com/Toblerity/Shapely/issues/568.  Reproducing the shapely error directly makes a tidier test case for the issue.
