### ISSUE TITLE
Zonal Stats Error

### ISSUE THREAD

**Issue by manuvare** [perrygeo/python-rasterstats#164]
Hi,

Running zonal_stats for a shape (with multiple grids) and extracting data from multiple tif, im gettig:
```
`
ValueError                                Traceback (most recent call last)
<ipython-input-1-4b8e24682b15> in <module>()
     35 
     36 with multiprocessing.Pool(cores) as pool:
---> 37     for nombre, resultado in pool.map(procesar_fichero, glob.glob("*.tif")):
     38         results[nombre] = resultado
     39     print ("Ultimos fichero {}".format(nombre))

C:\ProgramData\Anaconda3\lib\multiprocessing\pool.py in map(self, func, iterable, chunksize)
    264         in a list that is returned.
    265         '''
--> 266         return self._map_async(func, iterable, mapstar, chunksize).get()
    267 
    268     def starmap(self, func, iterable, chunksize=None):

C:\ProgramData\Anaconda3\lib\multiprocessing\pool.py in get(self, timeout)
    642             return self._value
    643         else:
--> 644             raise self._value
    645 
    646     def _set(self, i, obj):

Can't parse C:\xxx\xxxx\GRILLABSAS.shp as a geojson Feature object`
```

How to fix it?

I format the pc, before that, the code work properly. In addition i tried without multiprocessing and it works ok. So the issue is with multiprocessing

Win 10 64bits - Py 3.6 - Anaconda/Jupyter

i installed:
1)	conda install -c conda-forge gdal 
2)	conda install -c conda-forge rasterstats 
(i got the error, then after a few read, i update geopandas by:)
3)     conda install geopandas
(still getting the error).

Thanks

**Comment by perrygeo** [comment]
I don't have access to a Windows machine but I can take a look at the dataset. Can you provide the shapefile, preferably the smallest subset needed to cause the error.

**Comment by manuvare** [comment]
Attached

[Pruebas.zip](https://github.com/perrygeo/python-rasterstats/files/1841233/Pruebas.zip)

hope you could help me.

**Comment by perrygeo** [comment]
Thanks for providing the data. 

I'm not able to reproduce the error; works both with normal usage and adapting the `examples/multiproc.py` script. Confirmed working on OSX and Linux.

I suspect that the problem is in your multiprocessing script that calls zonal_stats. Can you share the code?

**Comment by manuvare** [comment]
sure

as i am using win, for multiprocessing i might need to define a .py with the simple zonal_stats commands and then a script with the multiprocessing and outputs.

```
import os, glob
from Ficheros import procesar_fichero #Ficheros.py has the zonal stats commands.
import time
import multiprocessing

print ("El programa ha iniciado")
t1=time.time()

rasterfolder = r'C:\img' #Location of the tif files
polys = r'C:\S.shp'  #Location of my grid shape

os.chdir(rasterfolder)

results = {}

print ("Entrando a la funcion Procesar")

cores=multiprocessing.cpu_count()

with multiprocessing.Pool(cores) as pool:
    for nombre, resultado in pool.map(procesar_fichero, glob.glob("*.tif")):
        results[nombre] = resultado
    print ("Ultimos fichero {}".format(nombre))
     
print ("El programa ha finalizado en: " , time.time()-t1)
```

**Comment by perrygeo** [comment]
Thanks for the code but I'm not able to reproduce this without the `procesar_fichero` function

**Comment by perrygeo** [comment]
Feel free to reopen when you can provide a test casae.
