### ISSUE TITLE
All touched issue

### ISSUE THREAD

**Issue by manuvare** [perrygeo/python-rasterstats#166]
Hi,

I madea grid over a tif file, where each pixel is a grid. If I´m understanding well, i think all touched True/False must get same results. Isn´t it?

Im not getting the same results selecting the feature by True or False, but i want to check if the error is in the grids construction.

Thanks for your comments

**Comment by perrygeo** [comment]
If the vector geometry is exactly aligned with the raster cell, it will technically "touch" all of the adjacent cells. So I would expect different results with `all_touched=True` (which would pick up adjacent cells) vs `all_touched=False` (only selecting cells where the centroid intersects)
