### ISSUE TITLE
support for raster objects

### ISSUE THREAD

**Issue by mwooten3** [perrygeo/python-rasterstats#168]
Would it be possible to add support for an input zonal raster as opposed to polygon? From my understanding the input polygon is rasterized anyways. Could this feature have the option for 8-member connectivity? Thank you for all your hard work!

**Comment by perrygeo** [comment]
This library is focussed only on vector-on-raster analysis. If you already have the zones and the data in raster format, you should use numpy techniques directly to calculate stats.
