### ISSUE TITLE
Question: user rasterinput in stead of vectorinput

### ISSUE THREAD

**Issue by daarende** [perrygeo/python-rasterstats#178]
Hello, great python package! 

Is there a possibility to foresee a raster with different zones as input in stead of a vector file? I suppose the code will rasterize the input polygons internally anyway? 

I have a raster with data and a raster with different zones. For each zone I want to calculate the zonal statistics on the data-raster. It's a bit stupid to convert the raster to a vector file if the package converts the vector file again to a raster...

**Comment by perrygeo** [comment]
The main purpose of this module is to bridge the gap between vector and raster data modeling for the zonal stats use case. If you've already got your data in raster format, I'd suggest using numpy arrays directly:

* iterate through the zones, creating a binary mask for each
* mask the raster data and compute statistics

The source code in https://github.com/perrygeo/python-rasterstats/blob/master/src/rasterstats/main.py should give you a decent starting point.
