### ISSUE TITLE
Computing row, column from x, y of a rotated numpy ndarray

### ISSUE THREAD

**Issue by jbellino-usgs** [perrygeo/python-rasterstats#182]
I'm experiencing problems with `zonal_stats` using a numpy ndarray and an affine object created from scratch. Apologies if I have misinterpreted something or if this is intended behavior, but it appears that the following code assumes othogonality with respect to the Cartesian coordinate axes and precludes the proper computation of row, column from an array that is in rotated coordinate space (i.e. `x` is not constant along columns and `y` is not constant along rows). Changing the row-rotation of my input affine seems to have little effect on the output and I'm wondering if this is why. 

The dataset I'm working with is on a regular grid of lon/lat (lon is constant along rows and lat is constant along columns). When I project into North America Albers Equal Area, for instance, the grid is rotated with respect to the x/y plane. A StackOverflow question with more background and example code can be found here: [https://stackoverflow.com/questions/55307096/compute-zonal-statistics-for-a-numpy-array-in-rotated-coordinate-space](https://stackoverflow.com/questions/55307096/compute-zonal-statistics-for-a-numpy-array-in-rotated-coordinate-space).

https://github.com/perrygeo/python-rasterstats/blob/910455cd7c9c21eadf464927db72b38ef62b7dfb/src/rasterstats/io.py#L137-L142

**Comment by perrygeo** [comment]
Rotation coefficients aren't supported at this time. Happy to work with you on a PR if you're like to submit a test case and a proposed solution.

**Comment by jbellino-usgs** [comment]
For my application it may be easier to place my data on a regular, non-rotated grid; but, if I decide otherwise I will revisit this idea. Closing this issue for the time being.
