### ISSUE TITLE
np.asscalar is deprecated

### ISSUE THREAD

**Issue by Zeitsperre** [perrygeo/python-rasterstats#183]
The call to np.asscalar() is raising a lot of warnings when categorical JSON output is requested.

```DeprecationWarning: np.asscalar(a) is deprecated since NumPy v1.16, use a.item() instead```

From what i can tell, it's simply a matter of updating `main.py`, lines 200 and 201 to be synonymous with current the NumPy API:
https://github.com/perrygeo/python-rasterstats/blob/910455cd7c9c21eadf464927db72b38ef62b7dfb/src/rasterstats/main.py#L200

Are there any reasons to not update base NumPy version for rasterstats?

**Comment by perrygeo** [comment]
I don't have an explicit policy about numpy version support but many folks are still on numpy 1.8 due to old LTS releases from the major OS.

**Comment by perrygeo** [comment]
@Zeitsperre if you'd like to submit a PR for the above change, I'm happy to test it on older numpy versions.

**Comment by Zeitsperre** [comment]
Hey @perrygeo, sure thing. I imagine the changes needed to support older and newer numpy won't take more than a few minutes. I'll test my changes locally before opening a PR here.

Thanks for maintaining this library btw!
