### ISSUE TITLE
how to add estadistics to attribute table?

### ISSUE THREAD

**Issue by FerCris** [perrygeo/python-rasterstats#187]
hi, i woul like to add my stadistic of 'max' to the atribute table of mi vector imput (.shp). When i obtain my max values:

`val =  zonal_stats(vector_dir, vulne_mask_dir, stats=['max'])`

"val" contains the values of the maximum for each poligon, but not in the same order than  the poligons in the atributes table.

how can I add each value with its corresponding polygon in the attribute table?

thank you very much in advance.

nota: esta es la tabla de atributos de mi vector de entrada
![image](https://user-images.githubusercontent.com/46815700/57370318-2dd9f980-7190-11e9-953c-4d95afe89979.png)

**Comment by giacfalk** [comment]
I'm following the discussion.

**Comment by perrygeo** [comment]
If the polygons are in a different order than `vals`, that is a bug. Unfortunately, nothing you've provided thus far indicates such a bug. @FerCris @giacfalk can you provide more details: Links to example datasets and reproducible code to recreate the error would be greatly appreciated. Thank you!

**Comment by giacfalk** [comment]
I don't have any bug but I am also curious if it would be possible to write the output of the zonal statistics as new columns to the shapefile, rather than generating a list of statistics or a new geojson file.

**Comment by perrygeo** [comment]
@giacfalk This library focusses on doing the analysis, other libraries handle the data serialization and IO operations. In this case, you would use `fiona` to write the return value to a shapefile. 

Why not include an option to write shapefiles internally? What if one user wants to write a shapefile with different parameters, another might need to write to a database, another might use the return value for further manipulation... and so on. This flexibility cannot be supported internally, at least not without adding significant complexity to the analysis code. Instead, we achieve this through composition and by interoperability with the rest of the python ecosystem.
