### ISSUE TITLE
unsupported operand type(s) for *: 'Affine' and 'Affine'

### ISSUE THREAD

**Issue by garethcao** [perrygeo/python-rasterstats#194]
Hi I met with the following problem when I use zonal_stats:

> stat = zonal_stats('.../Prefecture_Outline_2015_Project.shp','.../TEAK_Aspect_Mosaic.tif')

Then I received the following message:

> TypeError: unsupported operand type(s) for *: 'Affine' and 'Affine'

If I run the following code, it would not report error while no results:

> stat = rasterstats.gen_zonal_stats('.../Prefecture_Outline_2015_Project.shp','.../TEAK_Aspect_Mosaic.tif')

But the same message will emerge if I code as follows:

> stat = list(rasterstats.gen_zonal_stats('.../Prefecture_Outline_2015_Project.shp','.../TEAK_Aspect_Mosaic.tif'))

I do not know what the problem is and how to fix it. Could you please kindly provide some hints? Thanks a lot.

**Comment by perrygeo** [comment]
@garethcao can you provide the full error message?

The error message is related to the [affine](https://github.com/sgillies/affine) python library. Affine objects _should_ be usable with the `*` operator. For example

```
>>> Affine.identity() * Affine.identity()
Affine(1.0, 0.0, 0.0,
       0.0, 1.0, 0.0)
>>> affine.__version__
'2.2.2'
```

Can you confirm that you're using the latest version of affine? 

If you have access to a debugger, could you check the values of the affine objects at that point in the code? If there are Affine objects that cannot be `*` together, it's a bug in that library. 

The gen_zonal_stats function is a generator and will only execute when you iterate through it (with `list` in your case). So the different results are expected there.

**Comment by garethcao** [comment]
> @garethcao can you provide the full error message?
> 
> The error message is related to the [affine](https://github.com/sgillies/affine) python library. Affine objects _should_ be usable with the `*` operator. For example
> 
> ```
> >>> Affine.identity() * Affine.identity()
> Affine(1.0, 0.0, 0.0,
>        0.0, 1.0, 0.0)
> >>> affine.__version__
> '2.2.2'
> ```
> 
> Can you confirm that you're using the latest version of affine?
> 
> If you have access to a debugger, could you check the values of the affine objects at that point in the code? If there are Affine objects that cannot be `*` together, it's a bug in that library.
> 
> The gen_zonal_stats function is a generator and will only execute when you iterate through it (with `list` in your case). So the different results are expected there.

Thanks for your reply. My affine version is 2.2.2 as well. 

The complete error message is:

> ...\Anaconda3\lib\site-packages\rasterstats\io.py:300: UserWarning: Setting nodata to -999; specify nodata explicitly
> warnings.warn("Setting nodata to -999; specify nodata explicitly")
Traceback (most recent call last):

> File "<ipython-input-41-fc25eb45bc23>", line 1, in <module>
    stats = zonal_stats(".../Prefecture_Outline_2015/Prefecture_Outline_2015_Project.shp",'TEAK_Aspect_Mosaic.tif')

>  File "...\Anaconda3\lib\site-packages\rasterstats\main.py", line 31, in zonal_stats
    return list(gen_zonal_stats(*args, **kwargs))

>  File "...\Anaconda3\lib\site-packages\rasterstats\main.py", line 155, in gen_zonal_stats
    fsrc = rast.read(bounds=geom_bounds)

>  File "...\Anaconda3\lib\site-packages\rasterstats\io.py", line 309, in read
    self.band, window=win, boundless=True, masked=masked)

>  File "rasterio\_io.pyx", line 388, in rasterio._io.DatasetReaderBase.read

>  File "...\Anaconda3\lib\site-packages\rasterio\windows.py", line 91, in window_transform
    return transform(window, gtransform)

>  File "...\Anaconda3\lib\site-packages\rasterio\windows.py", line 306, in transform
    x - transform.c, y - transform.f) * transform

> TypeError: unsupported operand type(s) for *: 'Affine' and 'Affine'

I have also read your reply to another similar question:
> shp = gpd.read_file(".../Prefecture_Outline_2015_Project.shp",crs='4326')
> with rasterio.open("TEAK_Aspect_Mosaic.tif") as src:
>    array = src.read(1)
>    affine = src.affine
> zstats = zonal_stats(shp['SHI'], array, affine=affine)

And the error message this time is "AttributeError: 'DatasetReader' object has no attribute 'affine'".

Thanks for your replay again. Best wishes.

**Comment by perrygeo** [comment]
The error appears to be in the `rasterio.windows` module. What version of Rasterio are you using? `import rasterio; print(rasterio.__version__)`

**Comment by garethcao** [comment]
> The error appears to be in the `rasterio.windows` module. What version of Rasterio are you using? `import rasterio; print(rasterio.__version__)`

The version of Rasterio is 1.0.21

**Comment by garethcao** [comment]
> The error appears to be in the `rasterio.windows` module. What version of Rasterio are you using? `import rasterio; print(rasterio.__version__)`

One more information. The original error message is

> CPLE_OpenFailedError: Unable to open EPSG support file gcs.csv.  Try setting the GDAL_DATA environment variable to point to the directory containing EPSG csv files.

After reading that, I run "conda update gdal" in cmd and re-run the same code in spyder, then the error message turns into:

> TypeError: unsupported operand type(s) for *: 'Affine' and 'Affine'

**Comment by perrygeo** [comment]
@garethcao I'd suggest upgrading to the latest version of rasterio. If you still encounter this bug, let me know. If you could provide sample data and code to reproduce the problem, that would be great.
