### ISSUE TITLE
Ignoring Certain Pixels

### ISSUE THREAD

**Issue by cascadet** [perrygeo/python-rasterstats#195]
Hello - I love your package and have found it very helpful for my research! I have two questions about functionality. 

1. What does rasterstats do when I revalue NoData? For example, if I set no-data to 0 and a polygon overlaps a nodata value (no 0), is that pixel included when rasterstats calculates a statistic for that polygon? 

2. If not an already-built in as an argument, Is it possible to either build a User-defined Statistic that will ignore certain pixel values?

Essentially, I need to calculate the mean value for polygons overlaid on a raster and have raster_stats ignore certain pixels. 

Thank you again!

**Comment by perrygeo** [comment]
If the nodata value is set on your input raster dataset (see the output of `rio info` or `gdalinfo` and look for "nodata") then rasterstats will ignore those pixels.

A user-defined statistic uses the same nodata masking logic as other statistics, there's no need to add nodata handling to your custom stats.

**Comment by cascadet** [comment]
That makes a sense! Thank you for your quick reply and thank you for writing an excellent, well-documented package!
