### ISSUE TITLE
zone_func should be able return value

### ISSUE THREAD

**Issue by drnextgis** [perrygeo/python-rasterstats#199]
`zone_func` is meant to change values in-place, but I faced with the problem while working with integer raster and the following `zone_func`:

```
def zone_func(x):
    x[:] = x / 1000
```

All values become 0. This small snippet demonstrates the problem:

```
In [8]: import numpy as np 

In [9]: a = np.array([100, 200], dtype=np.uint) 

In [10]: a 
Out[10]: array([100, 200], dtype=uint64)

In [11]: a[:] = a / 1000
Out[12]: array([0, 0], dtype=uint64)
```

**Comment by perrygeo** [comment]
closed by #203
