### ISSUE TITLE
DeprecationWarning: Right multiplication will be prohibited in version 3.0

### ISSUE THREAD

**Issue by jens2121** [perrygeo/python-rasterstats#201]
`e, n = (col_stop, row_start) * affine` in rasterstats/io.py:156 is throwing a deprecation warning when running zonal statistics.

Can we assume this will be dealt with in the future, or is there something we can do on our side to deal with this.

Thanks in advance :)

**Comment by raymond-grointel** [comment]
Can we get a minor release with this fix please on pypi.
