### ISSUE TITLE
Multi-threading and zonal_stats

### ISSUE THREAD

**Issue by seffinier** [perrygeo/python-rasterstats#202]
Can I call rasterstats.zonal_stats in multiple threads ?
When I call it in a single thread, it is using 100% of one CPU but I tried calling it in about 10 threads and the CPU usage is limited to about 10% per CPU (I have 16 CPU's).
The raster file is different in each call while the shape file is often the same one (but I guess both are accessed in read-only)

I am running on CentOS 7 with Python 3.5.1, rasterstats 0.13.1 and rasterio 1.1.1

Is there a limitation ?

Thanks

**Comment by ircwaves** [comment]
Given your description, I'd assume you're experiencing limitation of input bandwidth.

**Comment by seffinier** [comment]
Thanks for your answer.
Doing some more tests, I noticed that the CPU's are much better used with big rasters (squares of about 11000x11000 pixels) than with smaller rasters (squares of about 6000x6000 pixels).
I am cutting the rasters because zonal_stats is drastically quicker on smaller rasters, but I am loosing part of the advantage because mutlithreading is less efficient...

**Comment by perrygeo** [comment]
An alternative is to use multiprocessing as show https://github.com/perrygeo/python-rasterstats/blob/master/examples/multiproc.py

The fact that your speed is so affected by raster size indicates that you might not have an optimal raster file layout - if possible use an internally-tiled format like GeoTiff in order to get consistent and fast access.

**Comment by seffinier** [comment]
Thanks for your answer
I am already using geoTiff's but I have to check the exact format
I tried already to load de raster in memory (gaining about 25%)
I will try pre-loading the shape as well

**Comment by perrygeo** [comment]
Thanks for the discussion! The thread-safety and threaded performance are characteristics of underlying Rasterio and GDAL libraries which are in turn influenced by data access patterns, environment variables and driver-specific behavior. I don't see anything I can do from this library to improve or even change the situation. Any solutions are going to be GDAL-specific so let's take the discussion over there.
