### ISSUE TITLE
Output percentage of pixels with missing value.

### ISSUE THREAD

**Issue by raajtilaksarma** [perrygeo/python-rasterstats#207]
Often when using `zonal_stats`, in a lot of use cases, it is important to know the amount of missing values within each shape intersecting a raster.
Hence it could be a good feature if we can output a number giving the percentage of missing pixels for an area overlapping the shape and raster. Also a value in the raster representing the missing value can be taken as an input to the function.

**Comment by perrygeo** [comment]
This already exists. There is a `nodata` statistic to get the count of "missing value" pixels. The nodata value is either defined by the raster dataset itself or through the `nodata` keyword argument. Example:

```
zonal_stats(..., nodata=-999, stats="nodata")
```

Will count all of the missing values encoded as -999
