### ISSUE TITLE
NO Data values in an array used in zonal stats computation

### ISSUE THREAD

**Issue by OpitiCalvin** [perrygeo/python-rasterstats#209]
I recently loaded an array on NDVI values computed from Descartes Labs API and needed to compute zonal stats. I even included the **no_data** parameter, set to -999. The mean values from zonal stats had values like: **4.904701496007352e+19** - meaning the default fill_value of 1e+20 was used instead of my set -999 for masked regions (which still should have been excluded). The computed zonal stats must have used both valid and masked pixels/cells for this. 

I even tried in-memory raster with rasterio but got the same outcome. BUT with gdal for in-memory raster, the right zonal stats were computed, excluding the masked pixels/no-data cells.

Could this be a bug as concerns how rasterio handles numpy.ndarrays and related transformation parameters or the zonal_stats module works best with gdal-based arrays/rasters?

**Comment by perrygeo** [comment]
It's possible. Can you provide a sample dataset and some code to demonstrate this?

**Comment by OpitiCalvin** [comment]
I figured out what I was doing wrong. I passed a normal array, instead of my masked array to the zonal stats function, hence propagating some of the erroneous values to the output
