### ISSUE TITLE
Installation ends with Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by alekfal** [perrygeo/python-rasterstats#210]
Hello,
I am trying to install rasterstats from pip3 to my Xubuntu 18.04 machine and I get a  Segmentation fault. My Python version is 3.6.9. Any suggestions on how to solve this? Bellow I posted the output.

<pre>pip3 install rasterstats
Collecting rasterstats
  Using cached https://files.pythonhosted.org/packages/bd/86/493e7794124d1048254bd3be562839506a4ea1777d7ce28313b1d2a24312/rasterstats-0.14.0-py3-none-any.whl
Collecting cligj&gt;=0.4 (from rasterstats)
  Using cached https://files.pythonhosted.org/packages/e4/be/30a58b4b0733850280d01f8bd132591b4668ed5c7046761098d665ac2174/cligj-0.5.0-py3-none-any.whl
Collecting fiona (from rasterstats)
  Using cached https://files.pythonhosted.org/packages/ec/20/4e63bc5c6e62df889297b382c3ccd4a7a488b00946aaaf81a118158c6f09/Fiona-1.8.13.post1-cp36-cp36m-manylinux1_x86_64.whl
Collecting simplejson (from rasterstats)
Collecting rasterio&gt;=1.0 (from rasterstats)
  Using cached https://files.pythonhosted.org/packages/be/e5/7052a3eef72af7e883a280d8dff64f4ea44cb92ec25ffb1d00ce27bc1a12/rasterio-1.1.2-cp36-cp36m-manylinux1_x86_64.whl
Collecting affine&lt;3.0 (from rasterstats)
  Using cached https://files.pythonhosted.org/packages/ac/a6/1a39a1ede71210e3ddaf623982b06ecfc5c5c03741ae659073159184cd3e/affine-2.3.0-py2.py3-none-any.whl
Collecting shapely (from rasterstats)
  Using cached https://files.pythonhosted.org/packages/20/fa/c96d3461fda99ed8e82ff0b219ac2c8384694b4e640a611a1a8390ecd415/Shapely-1.7.0-cp36-cp36m-manylinux1_x86_64.whl
Collecting numpy&gt;=1.9 (from rasterstats)
  Using cached https://files.pythonhosted.org/packages/62/20/4d43e141b5bc426ba38274933ef8e76e85c7adea2c321ecf9ebf7421cedf/numpy-1.18.1-cp36-cp36m-manylinux1_x86_64.whl
Collecting click&lt;8,&gt;=4.0 (from cligj&gt;=0.4-&gt;rasterstats)
  Using cached https://files.pythonhosted.org/packages/fa/37/45185cb5abbc30d7257104c434fe0b07e5a195a6847506c074527aa599ec/Click-7.0-py2.py3-none-any.whl
Collecting click-plugins&gt;=1.0 (from fiona-&gt;rasterstats)
  Using cached https://files.pythonhosted.org/packages/e9/da/824b92d9942f4e472702488857914bdd50f73021efea15b4cad9aca8ecef/click_plugins-1.1.1-py2.py3-none-any.whl
Collecting attrs&gt;=17 (from fiona-&gt;rasterstats)
  Using cached https://files.pythonhosted.org/packages/a2/db/4313ab3be961f7a763066401fb77f7748373b6094076ae2bda2806988af6/attrs-19.3.0-py2.py3-none-any.whl
Collecting munch (from fiona-&gt;rasterstats)
  Using cached https://files.pythonhosted.org/packages/cc/ab/85d8da5c9a45e072301beb37ad7f833cd344e04c817d97e0cc75681d248f/munch-2.5.0-py2.py3-none-any.whl
Collecting six&gt;=1.7 (from fiona-&gt;rasterstats)
  Using cached https://files.pythonhosted.org/packages/65/eb/1f97cb97bfc2390a276969c6fae16075da282f5058082d4cb10c6c5c1dba/six-1.14.0-py2.py3-none-any.whl
Collecting snuggs&gt;=1.4.1 (from rasterio&gt;=1.0-&gt;rasterstats)
  Using cached https://files.pythonhosted.org/packages/cc/0e/d27d6e806d6c0d1a2cfdc5d1f088e42339a0a54a09c3343f7f81ec8947ea/snuggs-1.4.7-py3-none-any.whl
Collecting pyparsing&gt;=2.1.6 (from snuggs&gt;=1.4.1-&gt;rasterio&gt;=1.0-&gt;rasterstats)
  Using cached https://files.pythonhosted.org/packages/5d/bc/1e58593167fade7b544bfe9502a26dc860940a79ab306e651e7f13be68c2/pyparsing-2.4.6-py2.py3-none-any.whl
Installing collected packages: click, cligj, click-plugins, attrs, six, munch, fiona, simplejson, affine, pyparsing, numpy, snuggs, rasterio, shapely, rasterstats
Segmentation fault (core dumped)
</pre>

**Comment by perrygeo** [comment]
@alekfal I suspect it's related to one of the dependencies with C-extensions. Can you reproduce this with a smaller set of libraries to help narrow it down? Try `fiona rasterio shapely numpy`

**Comment by alekfal** [comment]
Hello @perrygeo . Thank you for the reply. I've tried to install manually through pip all the requirements and I got a segmentation fault when I've tried to install simplejson.
Then I've re-install simplejson through pip and I didn't get an error, but still when installing rasterstats  the segmentation fault appears.

**Comment by perrygeo** [comment]
Can you reproduce this in a new clean virtual environment?

**Comment by alekfal** [comment]
Hello @perrygeo. I have created a new virtual environment as you suggested and the problem is solved. Thank you!
