### ISSUE TITLE
Conda Installation Failure on Python 3.8

### ISSUE THREAD

**Issue by pepeto** [perrygeo/python-rasterstats#223]
It seems like is not ready for Python 3.8. Do I have to downgrade the python version? I don't know how to solve the CUDA problem. Please help, tahnk you!

After executing:

conda install -c conda-forge/label/cf201901 rasterstats

or

conda install -c conda-forge/label/gcc7 rasterstats

I receive this message:

Specifications:

    rasterstats -> python[version='2.7.|3.5.|3.6.|3.4.']

Your python: python=3.8

If python is on the left-most side of the chain, that's the version you've asked for.
When python appears to the right, that indicates that the thing on the left is somehow
not available for the python version you are constrained to. Note that conda will not
change your python version to a different minor version unless you explicitly specify
that.

The following specifications were found to be incompatible with your system:

    feature:/win-64::__cuda==11.0=0
    feature:|@/win-64::__cuda==11.0=0

Your installed version is: 11.0

**Comment by perrygeo** [comment]
The packaging for conda is handled in an independent project: https://github.com/conda-forge/rasterstats-feedstock. I don't use or test on conda at all so I can't help with the specifics.

Based on the python version constraint above, I would guess that conda-forge is taking the versions in `setup.py` literally. 

https://github.com/perrygeo/python-rasterstats/blob/9ae7239d934075e322c2319734969b587844377a/setup.py#L58-L61

Adding more versions here might do the trick. I'll add that to the next release...
