### ISSUE TITLE
Installation  failure with conflict message under python 3.8.5 (Anaconda)

### ISSUE THREAD

**Issue by loicduffar** [perrygeo/python-rasterstats#241]
**Describe the bug**

Expected: Installation success of rasterstats in a new Anaconda3 plateform (python 3.8.5)
Happened: Installation failure with very long conflict message (Plese see partial screen copy below)

**To Reproduce**
1. How did you install rasterstats and its dependencies? 
under Windows 8.1 64 bits
by conda (with 2 channels: base + conda-forge)
in a new environment (Anaconda3-2020.11-Windows-x86_64.exe)
with only 2 more libraries installed just before: plotly, xarray

2. What datasets are necessary to reproduce the bug? Please provide links to example data if necessary. NOT APPLICABLE
3. What code is necessary to reproduce the bug? Provide the code directly below or provide links to it. NOT APPLICABLE

**PARTIAL SCREEN COPY** Hundreds of lines impossible to copy entirely (complete runinng takes more than 1hour)
image for the begining
+ video for the end

![install rasterstats](https://user-images.githubusercontent.com/32878622/112880264-83905580-90ca-11eb-8f0a-9cafc3ecf7e8.jpg)

https://user-images.githubusercontent.com/32878622/112880279-89863680-90ca-11eb-9ada-5f1fc632a993.mp4

**Comment by perrygeo** [comment]
This project builds wheels and source packages that are published to PyPI. While I don't explicitly discourage the use of conda, I don't have the bandwidth to support it.

The conda package distributions are managed entirely by the Anaconda project; I encourage you to check with the appropriate package maintainers to resolve this.

**Comment by sgoodm** [comment]
@loicduffar I was recently installing rasterstats using Conda and 3.8.x and encountered conflicts when including rasterstats in my base list of packages to install when the environment was created. Creating the environment first, installing all other packages, and then installing rasterstats using the conda-forge channel seemed to do the trick.

**Comment by loicduffar** [comment]
@sgoodm Thanks for sharing your experience.
It looks like you encountered a conflict issue while installing rasterstats with conda, and fixed it by installing it LAST.
But it is precisely by trying to install rasterstats after the other libraries that the process fails for me ....

Did I understand well your advice ?

**Comment by sgoodm** [comment]
@loicduffar Did you try explicitly installing rasterstats using the conda-forge channel? Generally conda vs conda-forge doesn't matter but there may be an newer version associated with conda-forge for some reason. Unfortunately, I did not look too deep into this as it just worked for me, so I don't have much more insight.

**Comment by loicduffar** [comment]
@sgoodm Yes the install is from conda-forge channel.
But I realize that the version is 0.14 on conda-forge (same as github version) while the version is 0.15 on pypi.
I don't know if it's important
