### ISSUE TITLE
Support for multibanded rasters

### ISSUE THREAD

**Issue by RyanConway91** [perrygeo/python-rasterstats#244]
Hello,

I have ~300 single band rasters with the same geometry (extent, cell size) and a shapefile with ~100000 zones. 

Based on current testing, running zonal_stats on all the rasters is going to take several days. 

If I could combine the rasters into a single multibanded raster, would the run time be reduced? Does zonal_stats work with multibanded rasters?

**Comment by debboutr** [comment]
Here's an [example](https://github.com/csc-training/geocomputing/blob/master/python/zonal_stats/zonal_stats_parallel.py
) that might help you out.
