### ISSUE TITLE
If polygons smaller than a pixel, stats not computed

### ISSUE THREAD

**Issue by Havi-muro** [perrygeo/python-rasterstats#262]
I've found that for the polygons that happen to be smaller than the image pixel, zonal_stats returns empty results. Although there are other packages to extract pixel values from points, in my case I have polygons of multiple sizes. If a polygon is larger than the pixel I need the zonal stats, but if it is smaller, just the pixel value would do. I suppose that it would be fairly easy to change (if min=max, just return one value). Thanks for this awesome package! Much faster than R.
![image](https://user-images.githubusercontent.com/11838692/185055652-5c5ff35f-39c9-4101-a1a2-b984a8618ca6.png)

**Comment by perrygeo** [comment]
See https://pythonhosted.org/rasterstats/manual.html#rasterization-strategy
