### ISSUE TITLE
segfault when importing rasterio

### ISSUE THREAD

**Issue by TimMcCauley** [perrygeo/python-rasterstats#269]
I'm not sure what is happening but as soon as I import `rasterio` I get a segfault (using the test data)

```python
>>> import rasterio # this will cause the segfault
>>> from rasterstats import zonal_stats
>>> 
>>> stats = zonal_stats(
...     "polygons.shp",
...     "slope.tif",
... )
[1]    3980 segmentation fault  python3
```

name = "rasterstats"
version = "0.17.0"

name = "rasterio"
version = "1.3.4"

**Comment by TimMcCauley** [comment]
I managed to advance a little on this issue... I'm not sure what is happening but as soon as I import `rasterio` I get a segfault:

```python
# import rasterio - this will cause the segfault
from rasterstats import zonal_stats

stats = zonal_stats(
    "fields.shp",
    "image.tif",
    band=9,
)
stats
```

name = "rasterstats"
version = "0.17.0"

name = "rasterio"
version = "1.3.4"

**Comment by jdmcbr** [comment]
@TimMcCauley This looks like it is a `rasterio` installation issue, and not `rasterstats`. The best place to ask `rasterio` installation questions is here: https://rasterio.groups.io/g/main
