### ISSUE TITLE
Partial polygon overlap in raster stats

### ISSUE THREAD

**Issue by engelmannjens** [perrygeo/python-rasterstats#27]
I am using the raster_stats module in python to calculate the mean carbon value for different sets of polygons. Here is the code that I am using:

```
africa_sat = 'E:/Research_Work/data/processing_data/carbon_satcchi/data/raw_data/africa_carbon_1km.tif'
name_clipshp = 'data/grid_clipped/' + name_hol + '_grid_cl.shp' # create object to point to clipped grid file

africa_stats = raster_stats(name_clipshp, africa_sat,stats=['mean'])
```

I have approximately 260 grid surface areas that I am employing. The grid areas have between ~10,000 polygons and ~40,000 polygons in them. Here is the error message I get for some of grids:

 Traceback (most recent call last):
 File "<stdin>", line 16, in <module>
 File "C:\Python27\lib\site-packages\rasterstats\main.py", line 153, in raster_stats
 rvds.SetGeoTransform(new_gt)
 AttributeError: 'NoneType' object has no attribute 'SetGeoTransform'

I do not get this error message, if the polygon overlaps completely with the raster image (tiff file) or if the polygon does not at all overlap with the polygon. However, if only a part of the polygon overlaps with the raster I get the error that is above.

Here is a link to a raster and shapefile that created the problem for me:

https://www.dropbox.com/sh/c80v8v576imd09f/7pSGN-p9lS

**Comment by abersh** [comment]
when upload .tif file to geonode "NoneType' object has no attribute 'GetGeoTransform' " how to fix pls anyone

**Comment by perrygeo** [comment]
@abersh You mention geonode and GetGeoTransform (a GDAL call) which are two unrelated software projects. If you have a question about rasterstats, please specify in more detail and open a new ticket. Thanks.

**Comment by abersh** [comment]
@perrygeo now i'm using geonode when uploading raster data in geotiff format  the system displayes this erorr  **"NoneType' object has no attribute 'GetGeoTransform' " **

**Comment by perrygeo** [comment]
Sorry @abersh , this repository is for python-rasterstats issue only. If you have geonode questions, please take them to the appropriate site: https://github.com/GeoNode/geonode/

**Comment by abersh** [comment]
@perrygeo thank you !!!

**Comment by naifgeo** [comment]
> This recent update should fix the issue. The problem was that one row of your polygons was exactly touching (but not overlapping) the raster - a case which I had not protected against.
> 
> The code has been updated and the corresponding test ('test_no_overlap') has been updated.

Hello Matthew, 
Thank you for your excellent lib 
if part of the grids are off the raster boundary will it cause a problem?
i'm using this function :
 average_dtm = rasterstats.zonal_stats(Grids_shp, dtm_array,
                                      affine = affine, stats = ['mean', 'min', 'max'],
                                      geojson_out = True)  
and the result i got is nonType object instead of the value.

**Comment by naifgeo** [comment]
![image](https://user-images.githubusercontent.com/102860180/161382353-1f29eb41-72fb-4f80-84d5-7e2f46250fdb.png)
