### ISSUE TITLE
allow fiona >= 1.9

### ISSUE THREAD

**Issue by vincentschut** [perrygeo/python-rasterstats#281]
Rasterstats currently has the fiona dependency pinned to <1.9 in project.toml.
Fiona 1.9 was released Jan 30. It would be nice if rasterstats could remove this restriction, so we can upgrade fiona in our projects.

**Comment by perrygeo** [comment]
The restriction is there for a reason, temporarily. For more context, see https://github.com/perrygeo/python-rasterstats/issues/274

> The upgrade to Fiona to 1.9.0 breaks the geojson_out feature which then returns fiona.model objects instead of GeoJSON dicts.

The fix should be straightforward, I just haven't had the time to implement it yet. I'd gladly accept a PR thought.

**Comment by SongshGeo** [comment]
Waiting for updates. Does someone have spare time to fix this?
