### ISSUE TITLE
pythonstats not importing in python 3.12

### ISSUE THREAD

**Issue by vcantarella** [perrygeo/python-rasterstats#298]
Hi,

Python stats has a numpy deprecation which makes it fail to work in python 3.12. Thank you!

```
module = importlib.import_module(name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "...\Lib\importlib\__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "C:\Users\vcant\miniconda3\envs\flopy-env-win\Lib\site-packages\rasterstats\__init__.py", line 2, in <module>
    from .main import gen_zonal_stats, raster_stats, zonal_stats
  File "C:\Users\vcant\miniconda3\envs\flopy-env-win\Lib\site-packages\rasterstats\main.py", line 8, in <module>
    import numpy.distutils.system_info as sysinfo
ModuleNotFoundError: No module named 'numpy.distutils'
```

**To Reproduce**

In a python 3.12 environment run:
```
import rasterstats
```

**Comment by perrygeo** [comment]
I can't reproduce this, I'm using python 3.12 locally for testing and development without any problems. Can you provide more detail on your python environment and how you installed it? This looks like something specific to your (conda?) environment.

With a fresh virtual environment and installing from pypi
```
$ python -m venv /tmp/env
$ source /tmp/env/bin/activate
$ pip install rasterstats
...
$ python
Python 3.12.4 (main, Jun  7 2024, 06:33:07) [GCC 14.1.1 20240522] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from rasterstats import zonal_stats
>>>
```

With a fresh virtual environment and installing from source
```
$ python -m venv /tmp/env
$ source /tmp/env/bin/activate
$ pip install -e .
...
$ python
Python 3.12.4 (main, Jun  7 2024, 06:33:07) [GCC 14.1.1 20240522] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from rasterstats import zonal_stats
>>>
```

If you're doing anything different, leave the details in a comment and maybe someone will have experience with that issue. I should note that Python's built-in virtualenv with pip is the only method officially supported (ie regularly tested) by this library; if you choose to use a different package management approach, you're flying solo.

That said, I need to add Python 3.12 to the test matrix. Thanks for the reminder.

**Comment by vcantarella** [comment]
Thank you @perrygeo !

Yes, sorry for that. I got messed up in a conda nightmare. Just checked with a fresh install and it works,

Thank again,
