### ISSUE TITLE
categorical=True appears to not work on Windows

### ISSUE THREAD

**Issue by shaystrong** [perrygeo/python-rasterstats#70]
On windows, when I apply the categorical=true flag, it will sometimes work and sometimes wont. I do not know how to ensure that is works. The vector file and raster have the same geometry. The output to a call like this:
out  = raster_stats('Parcels.shp','Landcover.tif',categorical=True) 
simply returns a listing like this:
{'_fid_': 1}
{'_fid_': 2}
{'_fid_': 3}
...

There are indeed 5 categories in the .tif file (I can open and see this in something like QGIS). I also have no problems with this working on OSX, however due to processing capability I have to get this working on windows. Could this all be fixed with a 0.6.2.exe?

(I am working with the raster_stats.0.3.2 on windows, only because the executable was available and installed correctly. The version 0.6.2 would not install correctly, as there was no .exe only an os-independent source)

**Comment by perrygeo** [comment]
How did you install raster_stats on your windows machine? If you use `pip install`, it should pick up the latest source version.

**Comment by perrygeo** [comment]
I'm assuming this worked for you? If not, reopen the ticket and we can keep debugging.
