### ISSUE TITLE
Remove osgeo.ogr and osr imports

### ISSUE THREAD

**Issue by ozak** [perrygeo/python-rasterstats#75]
@perrygeo It seems loading rasterstats causes ``GeoPandas`` to stop working properly. I can not see why this should be the case and it could be a ``GeoPandas`` (or my installation issue). See [here](https://github.com/geopandas/geopandas/issues/214) for the description and replication code and files.

**Comment by ozak** [comment]
Ok...it definitely seems to be a ``GeoPandas`` issue.

**Comment by perrygeo** [comment]
This [comment](https://github.com/geopandas/geopandas/issues/214#issuecomment-133534483) about osgeo imports causing problems points out the ultimate cause. It's still an issue that I need to address, though. 

I rid the code of `osgeo.gdal` but am still importing `osgeo.ogr` (which still provides a necessary abstraction layer for data not supported by fiona) and `osgeo.osr` for coordinate system handling.

If you don't mind I'll just edit this ticket, renaming it to reflect the new details..

**Comment by perrygeo** [comment]
https://github.com/Toblerity/Fiona/issues/92

**Comment by perrygeo** [comment]
The latest master is completely free of `osgeo.*` imports as of ed2a4d953459828168a740d1db53ddc0d2a33273
