### ISSUE TITLE
pip install fails for lack of cpl_conv.h 

### ISSUE THREAD

**Issue by foobarbecue** [perrygeo/python-rasterstats#77]
On Kubuntu 14.04, 
```$ sudo apt-get install python-numpy python-gdal```
```$ sudo pip install rasterstats```
leads to
```
rasterio/_base.c:271:22: fatal error: cpl_conv.h: No such file or directory

 #include "cpl_conv.h"

                      ^

compilation terminated.

error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

----------------------------------------
Cleaning up...
Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip_build_root/rasterio/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-g8C7sm-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip_build_root/rasterio
Storing debug log for failure in /home/aaron/.pip/pip.log
```

**Comment by foobarbecue** [comment]
Just needed to apt-get install libgdal-dev .

**Comment by perrygeo** [comment]
Thanks for the note, I'm working up some more detailed installation docs in #72 and this will help.

**Comment by juiceboxjoe** [comment]
Same thin ghappened when I was installing rasterio. apt-get install libgdal-dev also solved it for me! Now I' getting an import error from libgdal:

ImportError: /usr/lib/libgdal.so.20: undefined symbol: sqlite3_column_table_name

**Comment by norela** [comment]
Trying to install rasterstats on Ubuntu 16.10 using pip(aswell as  pip3) install returns:
`rasterio/_base.c:287:22: fatal error: cpl_conv.h: No such file or directory`
installing libgdal-dev fails:
`Unable to locate package libgdal-dev`
On Ubuntu 16.10 
`$ apt-cache search libgdal` returns 
libgdal20 - Geospatial Data Abstraction Library

It is installed and no libgdal20-dev is available.

**Comment by perrygeo** [comment]
@norela This is a Rasterio installation issue, one of the dependencies of python-rasterstats. Check out https://github.com/mapbox/rasterio#installation

To install Rasterio on a system without GDAL or a C compiler, you can use the latest Rasterio 1.0 release which comes with pre-compiled binary wheels:

```
pip install --pre "rasterio>=1.0a12"
```
