### ISSUE TITLE
cli should be able to accept any vector input that can be read by rasterstats.io.read_features (not just geojson feature collection)

### ISSUE THREAD

**Issue by fgassert** [perrygeo/python-rasterstats#81]
Perhaps you have a reason for only accepting feature collections, but this would be handy! 

e.g. mapshaper -dissolve dumps to a single multipolygon in geojson as output, so won't be accepted as input.

**Comment by perrygeo** [comment]
I think the CLI interface should be limited to GeoJSON for now (for interop with turf and fiona CLI). But there's no reason it should be limited to FeatureCollections only.

We should attempt to support Features and Geometries in addition to FeatureCollections. Thanks for noting this, I'll look into it shortly.

**Comment by perrygeo** [comment]
@fgassert That commit will allow geojson inputs but still outputs a FeatureCollection in every case.

Single geometries and features will result in a FeatureCollection of a single feature with zonalstats properties.

In terms of getting other input formats, I'd rather defer to a tool specializes in vector IO (ogr2ogr, fio, turf, etc) to get whatever other data into geojson.

**Comment by fgassert** [comment]
Excellent. Thanks!

**Comment by perrygeo** [comment]
I'm attempting to move the the input handling out of this module in favor of handling geojson inputs with a [`cligj`](https://github.com/mapbox/cligj). The only problem is that cligj doesn't support geometry inputs, only features and featurecollections. 

There is a workaround, you can use [`jq`](https://stedolan.github.io/jq/) to wrap a geometry in a feature. 
```
cat tests/data/geometry.geojson | jq '{"type": "Feature", "properties": {}, "geometry":.}'
```
@fgassert Does this work for your use case?

**Comment by perrygeo** [comment]
Either the jq route or the cligj route will ultimately be the solution here. We don't need to block rasterstats with this.
